export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  QUIZ_SCENE: 'QUIZ_SCENE',
  DRAG_DROP_SCENE: 'DRAG_DROP_SCENE',
} as const;
